name: eparkmo
description: E-Park Mo — Smart Parking System | Thesis Project 2026
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
