// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7DKAWGVDlESVWfIqC0NIQjJJhRyL7ZaI',
    appId: '1:253000162549:web:61ca761a4e14f1eaaa39bc',
    messagingSenderId: '253000162549',
    projectId: 'e-park-mo-fe42a',
    authDomain: 'e-park-mo-fe42a.firebaseapp.com',
    storageBucket: 'e-park-mo-fe42a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSPTAl2myRVHFDXUqOe7Tr4spa5mnXqqk',
    appId: '1:253000162549:android:bbc5d26d66e7b130aa39bc',
    messagingSenderId: '253000162549',
    projectId: 'e-park-mo-fe42a',
    storageBucket: 'e-park-mo-fe42a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1GcHQt0jViPYvkDq7xPorQNqvd920CNQ',
    appId: '1:253000162549:ios:a0dd1a9275ea1de3aa39bc',
    messagingSenderId: '253000162549',
    projectId: 'e-park-mo-fe42a',
    storageBucket: 'e-park-mo-fe42a.firebasestorage.app',
    iosBundleId: 'com.eparkmo.eparkmo',
  );
}
